[package]
name = "phazor_core"
version = "0.1.0"
edition = "2024"

[dependencies]
async-trait = "0.1.88"
serde = { version = "1", features = ["derive"] }
serde_json = "1"
tokio = "1.47.1"
uuid = { version = "1", features = ["v4", "serde"] }

